### ISSUE TITLE
Prometheus Sees a 503 error when trying to scrape endpoint page

### ISSUE THREAD

**Issue by BenB196** [AndreyVMarkelov/jira-prometheus-exporter#71]
Installed Prometheus Exporter for Jira trail to test it, when Prometheus attempts to scrape the site it get the following error:
```
server returned HTTP status 503 Service Unavailable
```

If I go directly to the metric link, the page loads and shows metrics.

Plugin Version: 1.0.39-jira8
Jira Version: v8.6.1
Prometheus Version: 2.20.0

Prometheus Scrape config:
```
- job_name: jira
  scheme: https
  metrics_path: '/plugins/servlet/prometheus/metrics'
  params:
    token: ['<128 character token>']
  static_configs:
  - targets:
    - "jira.domain.com"

```
